<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="net" nsURI="http://net.sf.latexdraw/3_0_0/" nsPrefix="net">
  <eSubpackages name="sf" nsURI="http://net.sf.latexdraw/3_0_0/net/sf" nsPrefix="net_sf">
    <eSubpackages name="latexdraw" nsURI="http://net.sf.latexdraw/3_0_0/net/sf/latexdraw"
        nsPrefix="net_sf_latexdraw">
      <eSubpackages name="model" nsURI="http://net.sf.latexdraw/3_0_0/net/sf/latexdraw/model"
          nsPrefix="net_sf_latexdraw_model">
        <eSubpackages name="interfaces" nsURI="http://net.sf.latexdraw/3_0_0/net/sf/latexdraw/model/interfaces"
            nsPrefix="net_sf_latexdraw_model_interfaces">
          <eClassifiers xsi:type="ecore:EClass" name="IShape" abstract="true" interface="true"/>
          <eClassifiers xsi:type="ecore:EClass" name="IDrawing" abstract="true" interface="true">
            <eOperations name="addShape">
              <eParameters name="sh" lowerBound="1" eType="#//sf/latexdraw/model/interfaces/IShape"/>
            </eOperations>
            <eOperations name="removeShape">
              <eParameters name="shape" eType="#//sf/latexdraw/model/interfaces/IShape"/>
            </eOperations>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
