<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fr" nsURI="http://fr.inria.triskell.IAFlowGraph/1_0_0/" nsPrefix="fr">
  <eSubpackages name="inria" nsURI="http://fr.inria.triskell.IAFlowGraph/1_0_0//fr/inria"
      nsPrefix="inria">
    <eSubpackages name="IAFlowGraph" nsURI="http://fr.inria.triskell.IAFlowGraph/1_0_0//fr/inria/IAFlowGraph"
        nsPrefix="IAFlowGraph">
      <eClassifiers xsi:type="ecore:EClass" name="IAFlowGraph">
        <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
            eType="#//inria/IAFlowGraph/Event" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Event">
        <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
            eType="#//inria/IAFlowGraph/Event" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//inria/IAFlowGraph/ResultingAction"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
            eType="ecore:EClass event.ecore#//malai/event/Event"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
            eType="ecore:EClass interaction.ecore#//malai/interaction/Transition"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EClass" name="ResultingAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
            eType="ecore:EClass action.ecore#//malai/action/Action"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionProduced" eType="#//inria/IAFlowGraph/Boolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
