<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org" nsURI="http://org.malai.interaction/1_0_0/" nsPrefix="org">
  <eSubpackages name="malai" nsURI="http://org.malai.interaction/1_0_0//org/malai"
      nsPrefix="org_malai">
    <eSubpackages name="interaction" nsURI="http://org.malai.interaction/1_0_0//org/malai/interaction"
        nsPrefix="org_malai_interaction">
      <eClassifiers xsi:type="ecore:EClass" name="Interaction">
        <eOperations name="onStarting"/>
        <eOperations name="onUpdating"/>
        <eOperations name="onStopping"/>
        <eOperations name="onAborting"/>
        <eOperations name="isRunning" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eOperations name="reinit"/>
        <eOperations name="executeTransition">
          <eParameters name="t" eType="#//malai/interaction/Transition"/>
        </eOperations>
        <eOperations name="getLastHIDUsed" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateCreation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initState" eType="#//malai/interaction/InitState"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
            eType="#//malai/interaction/State" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//malai/interaction/State"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" lowerBound="1"
            eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" lowerBound="1"
            eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="helpers" upperBound="-1"
            eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transition">
        <eOperations name="action"/>
        <eOperations name="isGuardRespected" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="inputState" lowerBound="1"
            eType="#//malai/interaction/State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outputState" lowerBound="1"
            eType="#//malai/interaction/State"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
            eType="ecore:EClass platform:/plugin/org.malai.model/src/main/metamodel/event.ecore#//malai/event/Event"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outputTransitions"
            upperBound="-1" eType="#//malai/interaction/Transition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AbortingState" eSuperTypes="#//malai/interaction/State"/>
      <eClassifiers xsi:type="ecore:EClass" name="TerminalState" eSuperTypes="#//malai/interaction/State"/>
      <eClassifiers xsi:type="ecore:EClass" name="StandardState" eSuperTypes="#//malai/interaction/State"/>
      <eClassifiers xsi:type="ecore:EClass" name="InitState" eSuperTypes="#//malai/interaction/StandardState"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
