<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org" nsURI="" nsPrefix="">
  <eSubpackages name="malai">
    <eSubpackages name="interactiveSystem">
      <eClassifiers xsi:type="ecore:EClass" name="interactiveSystem">
        <eStructuralFeatures xsi:type="ecore:EReference" name="instruments" upperBound="-1"
            eType="ecore:EClass instrument.ecore#//malai/instrument/Instrument" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
            eType="ecore:EClass action.ecore#//malai/action/Action"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
            eType="ecore:EClass event.ecore#//malai/event/Event"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
            eType="ecore:EClass widget.ecore#//malai/widget/Widget"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
