<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org" nsURI="http://org.malai.widget/1_0_0/" nsPrefix="org">
  <eSubpackages name="malai" nsURI="http://org.malai.widget/1_0_0//org/malai" nsPrefix="malai">
    <eSubpackages name="widget" nsURI="http://org.malai.widget/1_0_0//org/malai/widget"
        nsPrefix="org_malai_widget">
      <eClassifiers xsi:type="ecore:EClass" name="Widget" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//malai/widget/ContainerWidget"
            eOpposite="#//malai/widget/ContainerWidget/elements"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ContainerWidget" abstract="true"
          eSuperTypes="#//malai/widget/Widget">
        <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
            eType="#//malai/widget/Widget" containment="true" eOpposite="#//malai/widget/Widget/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ListWidget" abstract="true" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="ButtonWidget" abstract="true" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="TextWidget" abstract="true" eSuperTypes="#//malai/widget/Widget">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Slider" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProgressBar" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//malai/widget/Widget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//malai/widget/TextWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="TextArea" eSuperTypes="#//malai/widget/TextWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="TextField" eSuperTypes="#//malai/widget/TextWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Spinner" eSuperTypes="#//malai/widget/TextWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="MultiLineList" eSuperTypes="#//malai/widget/ListWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleLineList" eSuperTypes="#//malai/widget/ListWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Panel" eSuperTypes="#//malai/widget/ContainerWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Window" eSuperTypes="#//malai/widget/ContainerWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="DialogueBox" eSuperTypes="#//malai/widget/Window"/>
      <eClassifiers xsi:type="ecore:EClass" name="SplitPane" eSuperTypes="#//malai/widget/ContainerWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="TabbedPanel" eSuperTypes="#//malai/widget/ContainerWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//malai/widget/ButtonWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToggleButton" eSuperTypes="#//malai/widget/Button"/>
      <eClassifiers xsi:type="ecore:EClass" name="Menu" eSuperTypes="#//malai/widget/ButtonWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="CheckBox" eSuperTypes="#//malai/widget/ButtonWidget"/>
      <eClassifiers xsi:type="ecore:EClass" name="RadioButton" eSuperTypes="#//malai/widget/ButtonWidget #//malai/widget/Button"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToggleMenu" eSuperTypes="#//malai/widget/Menu"/>
      <eClassifiers xsi:type="ecore:EClass" name="RadioMenu" eSuperTypes="#//malai/widget/Menu"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
