<?xml version="1.0" encoding="UTF-8"?>
<org_malai_action:ActionModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:org_malai_action="http://org.malai.action/1_0_0//org/malai/action">
  <actions undoable="true" execute="drawing.addShape(shape);&#xA;" canDo="shape!=null &amp;&amp; drawing!=null" undo="drawing.removeShape(shape);" redo="drawing.addShape(shape);">
    <clazz name="AddShape">
      <eStructuralFeatures xsi:type="ecore:EReference" name="shape">
        <eType xsi:type="ecore:EClass" href="../model.ecore#//sf/latexdraw/model/interfaces/IShape"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="drawing">
        <eType xsi:type="ecore:EClass" href="../model.ecore#//sf/latexdraw/model/interfaces/IDrawing"/>
      </eStructuralFeatures>
    </clazz>
  </actions>
  <actions>
    <clazz name="SelectPencilEditingStyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pencil">
        <eType xsi:type="ecore:EClass" href="../instruments/pencil.instrument#//@clazz"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newEditingStyle">
        <eType xsi:type="ecore:EEnum" href="../instruments/pencil.instrument#//@helpers.0"/>
      </eStructuralFeatures>
    </clazz>
  </actions>
  <actions modifyInstrument="true">
    <clazz name="CustomisePencil">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pencil">
        <eType xsi:type="ecore:EClass" href="../instruments/pencil.instrument#//@clazz"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="//@helpers.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue">
        <eType xsi:type="ecore:EDataType" href="../interactions/events.event#//@helpers.0"/>
      </eStructuralFeatures>
    </clazz>
  </actions>
  <helpers xsi:type="ecore:EEnum" name="PencilParameter">
    <eLiterals name="THICKNESS"/>
  </helpers>
  <helpers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
</org_malai_action:ActionModel>
